
title: ryankwon.github.com
email: dataspheres@gmail.com
description: 

baseurl: "" # the subpath of your site, e.g. /blog
url: http://ryankwon.github.io # the base hostname & protocol for your site

twitter_username: dataspheres
github_username:  ryanhskwon

# Build settings
markdown: redcarpet
highlighter: rouge

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md